In [31]:
#cartesian coordinate
import numpy as np
import math
from sympy import *
np.set_printoptions(precision=16, suppress=True)


In [32]:
#先求向量之间的夹角,a=I1-I6,b=I3-I5, c=I2-I4
vector1=np.array(
 [[1.274358746,-1.884935723,1.589553654],
[2.269583389,-0.161159369,-1.589563272],
[0.995219789,2.046097987,1.589556782]])

In [33]:
#求normal1的模长
v_module = np.sqrt(np.sum(vector1*vector1,axis=1))
v1=v_module [0]
v2=v_module [1]
v3=v_module [2]
print(v_module )
print(v1)

[2.7755456602788895 2.7755526472276744 2.775548623970557 ]
2.7755456602788895


In [34]:
#单位化
AA=vector1[0]/v1
BB=vector1[1]/v2
CC=vector1[2]/v3
#print(AA,BB,CC)
vector=np.array([AA,BB,CC])
print(vector)

[[ 0.4591380946231493 -0.6791225775801504  0.5726995151793972]
 [ 0.8177050402077384 -0.0580638847405658 -0.5727015387684017]
 [ 0.3585668722950671  0.7371868643659204  0.5727000306433334]]


In [35]:
mo=np.dot(vector[0],vector[1])
print(mo)
print(vector[1])
print(vector[2])
A=np.dot(vector[0],vector[1])/np.sqrt(np.dot(vector[0],vector[0])/np.sqrt(np.sum(np.dot(vector[1],vector[1]))))

C=np.dot(vector[0],vector[2])/np.sqrt(np.sum(np.dot(vector[0],vector[0]))/np.sqrt(np.sum(np.dot(vector[2],vector[2]))))
print(A,C) 
A1=vector[0,0]*vector[1,1]-vector[0,1]*vector[1,0]
B1=vector[1,0]*vector[2,1]-vector[1,1]*vector[2,0]
C1=vector[0,0]*vector[2,1]-vector[0,1]*vector[2,0]
print(A1,B1,C1)

0.08688613559889807
[ 0.8177050402077384 -0.0580638847405658 -0.5727015387684017]
[0.3585668722950671 0.7371868643659204 0.5727000306433334]
0.08688613559889807 -0.008023503053210368
0.5286626131999582 0.6236212001116774 0.5819814308340613


In [36]:
B=np.dot(vector[1],vector[2])/np.sqrt(np.sum(np.dot(vector[1],vector[1]))/np.sqrt(np.sum(np.dot(vector[2],vector[2]))))
angle_bc=np.degrees(np.arccos(B))
print(angle_bc)

94.44994780253543


In [37]:
angle_ab=np.degrees(np.arccos(A))
angle_bc=np.degrees(np.arccos(B))
angle_ac=np.degrees(np.arccos(C))
print(angle_ab,angle_bc,angle_ac)

85.01550617474109 94.44994780253543 90.45971779446077
